# Generated by Django 3.0.7 on 2020-06-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='blog_content',
            new_name='code_content',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='blog_posted',
            new_name='code_posted',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='blog_title',
            new_name='code_title',
        ),
    ]
