# Generated by Django 3.0.7 on 2020-06-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200629_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_posted',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='code_posted',
            new_name='date_posted',
        ),
    ]
