# Generated by Django 3.0.7 on 2020-06-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200629_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='blog_content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='date_posted',
            new_name='blog_posted',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='blog_title',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='content',
            new_name='code_content',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='date_posted',
            new_name='code_posted',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='title',
            new_name='code_title',
        ),
    ]
