# Generated by Django 3.0.7 on 2020-07-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200704_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
